# Generated by Django 4.1.4 on 2023-12-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=256)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
