# Generated by Django 4.1.4 on 2024-01-13 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Congregacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSordo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado del Sordo',
                'verbose_name_plural': 'Estados de Sordos',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Publicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('telegram_chatid', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telegram Chat ID')),
                ('congregacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicadores', to='webTerritorios.congregacion', verbose_name='Congregacion')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeniasTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Señas',
                'verbose_name_plural': 'Tipos de Señas',
            },
        ),
        migrations.CreateModel(
            name='TipoLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Log',
                'verbose_name_plural': 'Tipos de Log',
            },
        ),
        migrations.CreateModel(
            name='Territorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('congregacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territorios', to='webTerritorios.congregacion', verbose_name='Congregacion')),
            ],
            options={
                'verbose_name': 'Territorio',
                'verbose_name_plural': 'Territorios',
            },
        ),
        migrations.CreateModel(
            name='Sordo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=50)),
                ('anio_nacimiento', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
                ('gps_latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('gps_longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('estado_sordo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sordos_de_este_estado', to='webTerritorios.estadosordo', verbose_name='Estado del Sordo')),
                ('genero_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sordos_de_este_genero', to='webTerritorios.genero', verbose_name='Genero')),
                ('publicador_estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='webTerritorios.publicador', verbose_name='Estudia Con')),
                ('senias_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sordos_de_este_tipo', to='webTerritorios.seniastipo', verbose_name='Tipo de Señas')),
                ('territorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sordos', to='webTerritorios.territorio', verbose_name='Territorio')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('publicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_de_este_publicador', to='webTerritorios.publicador', verbose_name='Publicador')),
                ('tipo_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_de_este_tipo', to='webTerritorios.tipolog', verbose_name='Tipo de Log')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(auto_now=True, null=True)),
                ('publicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_de_este_publicador', to='webTerritorios.publicador', verbose_name='Publicador')),
                ('territorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_de_este_territorio', to='webTerritorios.territorio', verbose_name='Territorio')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
    ]
