# Generated by Django 5.0.1 on 2024-03-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webTerritorios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='publicador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='publicador',
            name='telefono',
        ),
    ]
