# Generated by Django 5.0.1 on 2025-04-21 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webTerritorios', '0002_auto_20250109_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='territorio_nombre_texto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='territorio_numero_texto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
