# Generated by Django 5.0.1 on 2024-03-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webTerritorios', '0003_sordo_activo_alter_asignacion_fecha_fin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregacion',
            options={'verbose_name': 'Congregación', 'verbose_name_plural': 'Congregaciones'},
        ),
        migrations.RemoveField(
            model_name='sordo',
            name='activo',
        ),
    ]
