# Generated by Django 5.0.1 on 2025-04-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webTerritorios', '0003_asignacion_territorio_nombre_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sordo',
            name='mejorVisitar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mejor Visitar'),
        ),
    ]
