# Generated by Django 5.0.1 on 2024-03-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webTerritorios', '0004_alter_congregacion_options_remove_sordo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicador',
            name='nombre',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
