# Generated by Django 5.0.1 on 2024-04-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webTerritorios', '0006_alter_publicador_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sordo',
            name='genero_id',
        ),
        migrations.RemoveField(
            model_name='sordo',
            name='senias_tipo',
        ),
        migrations.RemoveField(
            model_name='sordo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='sordo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='sordo',
            name='detalles_direccion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='sordo',
            name='detalles_familia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sordo',
            name='detalles_sordo',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='sordo',
            name='tipo_senias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sordo',
            name='nombre',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='SeniasTipo',
        ),
    ]
